### ISSUE TITLE
App crashes on installation

### ISSUE THREAD

**Issue by cbho** [exeldro/com.insights.aggregate#1]
Homey FW 1.5.6-rc.7

(node:22671) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): no_auth_method_found
(node:22671) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/app.js:92
this.calculating = aggregations.length;
^

TypeError: Cannot read property 'length' of null
at AggregatedInsightsApp.calculateAggregations (/app.js:92:35)
at Timeout._onTimeout (/app.js:14:29)
at ontimeout (timers.js:475:11)
at tryOnTimeout (timers.js:310:5)
at Timer.listOnTimeout (timers.js:270:5)

Exit code: 1
Exit signal: null

**Comment by exeldro** [comment]
Bug found and fixed
