### ISSUE TITLE
Open feedback beta 0.0.3

### ISSUE THREAD

**Issue by rnldnkp** [exeldro/com.insights.aggregate#2]
First of all, great work! 

You made somewhat what I describe in https://forum.athom.com/discussion/comment/66014 or on https://github.com/athombv/homey/issues/2084 so I really like the idea of this App

In this issue I would like to give some open feedback about the beta. Maybe I did something wrong, or it could help you make the app even better.

My list so far, have used it for like 10 minutes. So please do not take them too seriously for now :P 

1. The app asks for full homey permissions. Is this needed in the production version? Maybe else you cannot read the insights? If so, I think you should not this on the App page.
2. At first I couldn't add a aggregated insight. This is because the 'log' list was empty. An app reboot fixed this. Might have been to fast?
3. I see some of undefined/logs, guess this is homey's fault. Pretty sure these are from disabled apps. Guess you should filter these out since homey hides them as well.
4. I can choose what the start date is, but not the start time. Guess you should note that I have to choose today's date to start right now?
5. The time format seems to change after you save and reload the page. When saving "Wed Jan 17 2018 01:00:00 GMT+0100 (CET)". Next hour is "2018-01-17T00:00:00.000Z"?

Now let's wait and see what happens after some time. Can't wait ;)

**Comment by rnldnkp** [comment]
4. >> Ah, wait. It's not the start date, but the first date it should use to read insights. Like from insight you already have for months! My bad!

**Comment by exeldro** [comment]
Thank you for trying my app.

1. The app needs the "homey:manager:api" permission to get an owner api token to get the logs from other apps. I will add this to the app page.
2. The app gets all available logs on startup, but it take some time. So you were probably too fast. I will add a loading message.
3. When making the app I did not have any disabled apps. Tested with disabled apps and that gives 'undifined'. I will try and find a better way to determine the log name.
4. The start date is indeed the first date it will read the insight logs.
5. I will add some date and time formatting.

**Comment by Swiftnesses** [comment]
Same issue here with no logs in dropdown... Still waiting...

Update: A restart fixed it.

**Comment by exeldro** [comment]
Found the bug for 2. It starts loading the logs before it has the api token. Will fix coming weekend.

**Comment by exeldro** [comment]
bugs fixed in version 0.0.5

**Comment by Swiftnesses** [comment]
I noticed I get many 'undefined' options under my logs (I assume these are because they're custom attributes).

**Comment by exeldro** [comment]
the many undefined is that in version 0.0.3? It should be fixed in 0.0.5

**Comment by Swiftnesses** [comment]
Stupid question, but is it not possible to use these in flows? Or are my eyes failing me (it's been a long day!)

**Comment by exeldro** [comment]
No, I did not yet add flow actions or conditions. What kind of flows do you want to create?

**Comment by Swiftnesses** [comment]
Personally, I would have used the cards to reset 'aggregated insight' items, rather than specify it when they're created - more flexible IMHO. Controlling the items via cards allows much more control. Currently, I'd like to see value as tokens, so I can use them in flows. I think adding the items, a name and aggregation method, and then using cards to start / stop / reset items would be fantastic!

**Comment by exeldro** [comment]
I made a new issue for the flows #3

**Comment by exeldro** [comment]
with version 0.0.5 published I'm gonna close this issue
