### ISSUE TITLE
Difference aggregation produces flat (zero) insights

### ISSUE THREAD

**Issue by rnldnkp** [exeldro/com.insights.aggregate#4]
I tried like all combinations I could think of, but all I get is a flat line of zero values for my power meters.
I did however get 'Average' and 'Sum' working for two there types of values (beter logic and temp sensor).

Example, Youless powermeter.
<img width="1203" alt="schermafbeelding 2018-01-19 om 19 18 08" src="https://user-images.githubusercontent.com/25203654/35165165-88d316a4-fd4d-11e7-92ea-c0ebb2f3c4ae.png">

Then add these two to be sure (since peak does not have values at night)
<img width="1211" alt="schermafbeelding 2018-01-19 om 19 29 25" src="https://user-images.githubusercontent.com/25203654/35165672-8ce5c6a4-fd4f-11e7-81f1-4c5e20134914.png">

While waiting I get
some "Missing logs for x", and "x log value:NaN Fri Jan 19 2018 04:00:00 GMT+0100(CET)", although it continues.

And, when it's done, it looks like this
<img width="1205" alt="schermafbeelding 2018-01-19 om 19 38 47" src="https://user-images.githubusercontent.com/25203654/35165929-688a6f98-fd50-11e7-99b5-1a278e469226.png">
<img width="1213" alt="schermafbeelding 2018-01-19 om 19 39 31" src="https://user-images.githubusercontent.com/25203654/35165953-804a23f8-fd50-11e7-8051-8f3e1f23e755.png">

Could you help me out how to do it the right way?
I understand the second start/middle/end, but what about the first start/end (next to 'log')?

Using 0.0.5 now

**Update**: Changed title to something more useful for the issue (since I didn't know it was a issue)

**Comment by exeldro** [comment]
I found the bugs in the difference aggregation fixing them atm

**Comment by exeldro** [comment]
The start/end next to log is for aggregation method average. It calculates the average weighing in the time the value has been active. The active time of a value can be before or after the log moment.

**Comment by exeldro** [comment]
version 0.0.6 fixes the difference aggregation

**Comment by rnldnkp** [comment]
Thanks for the info and the fix

**Comment by exeldro** [comment]
version 0.1.0 is now published.

**Comment by rnldnkp** [comment]
works like a charm!
<img width="1214" alt="schermafbeelding 2018-01-22 om 23 47 20" src="https://user-images.githubusercontent.com/25203654/35248513-a67dfefc-ffce-11e7-9535-2ea0315e9339.png">

Manual better logic calculation (flow 0:00 every day) vs your app (in like 10 seconds) :)
