### ISSUE TITLE
deleting two (or more) aggregates insights

### ISSUE THREAD

**Issue by rnldnkp** [exeldro/com.insights.aggregate#5]
In version 0.0.5 I cannot delete more than one Aggregated Insight rule.
First one works, logs says 'deleted'. App refresh and the rule is indeed gone.

Second delete does show the popup but doesn't do anything.

When refreshing the app view, it is still there. Showing me this
<img width="369" alt="schermafbeelding 2018-01-19 om 19 45 25" src="https://user-images.githubusercontent.com/25203654/35166276-a51ca010-fd51-11e7-9164-74e4972a08c0.png">

Waiting for 2 minutes and then deleting second one does not help.
An app reboot however works instantly (for one rule). Then reboot app again and delete 3rd one, etc.

Might it be failing to delete the rule in the background? I think of this since it doesn't delete the aggregated insights already calculated (insight view)

**Comment by exeldro** [comment]
I think the app crashed and was not processing the delete request anymore. I have not been able to reproduce the bug yet.

**Comment by exeldro** [comment]
In version 0.1.0 I made better error handling/recovering

**Comment by rnldnkp** [comment]
Might also had to do with #4 will also test this once the update is available

**Comment by exeldro** [comment]
version 0.1.0 is now published.

**Comment by rnldnkp** [comment]
Works now, can delete one after another without any issue.

Just a note (not really for this bug I guess): after the upgrade two abandoned aggregated logs got stuck (no corresponding rule) which I cannot delete without removing the app. Not sure if this could happen again, but maybe you could check and remove them anyhow since there's no way to update them.
Left them there for now if you want to test.

**Comment by exeldro** [comment]
I will make a check for abandoned aggregated logs on startup of the app

**Comment by exeldro** [comment]
version 0.1.1 deletes abandoned aggregated logs

**Comment by exeldro** [comment]
version 0.1.1 is now published

**Comment by rnldnkp** [comment]
Hmm, not sure if it was my fault. But last night I found the app disabled (after the update).
After enabling no rules or abandoned logs were present. Not sure thought if I might have removed all (just 2) rules the day before.. But I don't think so.

So, removing logs work. If nobody else experienced what I had I guess this is done. ;)
