### ISSUE TITLE
Cannot aggregate a aggregated log until I restart the app

### ISSUE THREAD

**Issue by rnldnkp** [exeldro/com.insights.aggregate#7]
In version 0.1.1 I cannot aggregate a just created log. 

So, you create a rule, you fix this: https://github.com/exeldro/com.insights.aggregate/issues/6
You wait until it is finished, check the insights and see it's there.

Next you try to create a aggregated log of the log you just created.
result: Aggregated log not shown in the list, so you cannot select it.

Solution: restart app, it will be right there. 
This goes for every rule you make (not just the first)

**Comment by exeldro** [comment]
fixed in version 0.1.2

**Comment by exeldro** [comment]
version 0.1.2 is published now
